<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://alert-on-air.ws.com.co"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://alert-on-air.ws.com.co"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="AlertOnAir">
        <plnk:role name="AlertOnAirEndpoint" portType="tns:AlertOnAirEndpoint"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://alert-on-air.ws.com.co" location="alert-on-air.wsdl"/>
</wsdl:definitions>
